### ISSUE TITLE
New MTU Validation breaks with existing networks

### ISSUE THREAD

**Issue by jwmay2012** [kubernetes-sigs/cluster-api-provider-gcp#1312]
/kind bug

**What steps did you take and what happened:**
Create a cluster with an existing Network and Subnet.

**What did you expect to happen:**

MTU webhook validation to pass.

**Anything else you would like to add:**

`kube-apiserver`
```
W0917 15:23:31.574175       1 dispatcher.go:225] rejected by webhook "validation.gcpcluster.infrastructure.cluster.x-k8s.io": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"validation.gcpcluster.infrastructure.cluster.x-k8s.io\" denied the request: GCPCluster.infrastructure.cluster.x-k8s.io \"gce-us1c-h\" is invalid: spec.Network.Mtu: Invalid value: 0: field cannot be lesser than 1300", Reason:"Invalid", Details:(*v1.StatusDetails)(0xc00a587920), Code:422}}
```

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPCluster
metadata:
  name: gce-us1c-h
  namespace: myproject
spec:
  loadBalancer:
    loadBalancerType: Internal
  network:
    autoCreateSubnetworks: false
    hostProject: mysharedvpchostproject
    name: mysharedvpchostproject
    subnets:
    - name: myproject-gce-us1c-h-sub
    mtu: 1460 # shouldn't need to be set, but fails even if it is
  project: myproject
  region: us-central1
```

The validation fails when `GCPCluster.Spec.network.mtu` is set to `1460`, or unset (as it should be in this case).

This PR introduced it: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1262

**Environment:**

- Cluster-api version: latest `main` [67ff6d8](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/commit/67ff6d8b42b7624226390705e4fe30e2000bceca)
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): v1.29.2
- OS (e.g. from `/etc/os-release`):
