### ISSUE TITLE
Error message saying EC2 instead of GCE

### ISSUE THREAD

**Issue by nader-ziada** [kubernetes-sigs/cluster-api-provider-gcp#243]
/kind bug

**What steps did you take and what happened:**
Checking the GCPmachine object yaml

for example when a GCE vm failed I got the following status
```
status:
  errorMessage: EC2 instance state "TERMINATED" is unexpected
  errorReason: UpdateError
  instanceState: TERMINATED
```

**What did you expect to happen:**
Should say `GCE instance` since this is the GCP provider

**Environment:**

- Cluster-api version: v1alpha3
