### ISSUE TITLE
Implement GCPMachinePool using MIGs

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-gcp#297]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Implement GCPMachinePool using [Managed Instance Groups](https://cloud.google.com/compute/docs/instance-groups/). The GCPMachinePool implementation should follow the same package / group structure as CAPI and be added to the exp package, the experimental feature package. The feature should be gated using the MachinePool flag used in CAPI.

See also: kubernetes-sigs/cluster-api-provider-azure#483 and [CAPI Machine Pool Proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20190919-machinepool-api.md)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jayesh-srivastava** [comment]
Hey, would like to work on this. Can I assign it myself?

**Comment by evanfreed** [comment]
@jayesh-srivastava just curious if you are still working on this? Myself or another colleague of mine might have some cycles to pick this up if you need any help.

**Comment by AverageMarcus** [comment]
@CecileRobertMichon could we also add as a requirement to this ticket that (if actually merged) the [externally-managed autoscaller annotation](https://github.com/kubernetes-sigs/cluster-api/pull/7107) is also supported / implemented as part of this?

**Comment by CecileRobertMichon** [comment]
@AverageMarcus added a note in description

**Comment by AverageMarcus** [comment]
Perfect! Thank you!

**Comment by nsilve** [comment]
I have pinged @jayesh-srivastava via Slack and he told me that he is not able to work on this issue due to personal commitments. @evanfreed and myself are going to work on it unless there is any objection.

**Comment by nsilve** [comment]
Pending blockers:
- https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/643
- https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/71
- https://github.com/kubernetes-sigs/cluster-api/pull/7107

**Comment by nsilve** [comment]
Azure does not support any kind of templating for instance creation, so all the configuration should be included into VMSS (so into AzureMachinePool). But both AWS and GCP have discrete template resources for ASG (launch template)/MIG (instance template) so we are having the following options:
1. manage GCP instance templates internally to GCP Machine Pool controller (like [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/exp/controllers/awsmachinepool_controller.go#L246))
2. manage GCP instance templates via a separate GCP Instance Template controller
3. something else

Moreover, based on [GCP documentation](https://cloud.google.com/compute/docs/instance-templates), instance templates can be used to create both virtual machine (VM) instances and managed instance groups (MIGs).  That means that we could probably define `GCPMachineTemplate` and use them directly into `GCPMachinePool` (not tested)
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: workload
spec:
  template:
    spec:
      image: projects/elastic-esp-dev/global/images/capi-ubuntu-2004-k8s-v1-24-1
      instanceType: n2-standard-2

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachinePool
spec:
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: GCPMachineTemplate
      name: workload
```

Any ideas/comments/objections?
