### ISSUE TITLE
Generated addons.yaml file is incorrect and cannot be applied

### ISSUE THREAD

**Issue by oxddr** [kubernetes-sigs/cluster-api-provider-gcp#40]
The generated addons.yaml file cannot be applied (either by passing to clusterctl or via kubectl apply). Output:

storageclass.storage.k8s.io/standard created
serviceaccount/glbc created
deployment.extensions/l7-default-backend created
configmap/ingress-controller-config created
service/default-http-backend created
deployment.extensions/l7-lb-controller created
secret/glbc-gcp-key created
Error from server (NotFound): error when creating "examples/google/out/addons.yaml": the server could not find the requested resource
Error from server (NotFound): error when creating "examples/google/out/addons.yaml": the server could not find the requested resource

Generated addons.yaml, when passed to clusterctl causing it to fail cluster creation.

**Comment by oxddr** [comment]
This is the problematic part of [addons.yaml.template](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/master/clusterctl/examples/google/addons.yaml.template), but I have no idea what's wrong in here. 

```
apiVersion: rbac.authorization.k8s.io/
kind: ClusterRole
metadata:
  name: system:controller:glbc
rules:
- apiGroups: [""]
  resources: ["secrets", "endpoints", "services", "pods", "nodes", "namespaces"]
  verbs: ["describe", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["events", "configmaps"]
  verbs: ["describe", "get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["extensions"]
  resources: ["ingresses/status"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/
kind: ClusterRoleBinding
metadata:
  name: system:controller:glbc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:glbc
subjects:
- kind: ServiceAccount
  name: glbc
  namespace: kube-system
```
