### ISSUE TITLE
Custom V-Net addition to docs

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-gcp#419]
/kind documentation

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Adding a Custom Virtual Network documentation GCP

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Refer to https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/docs/book/src/topics/custom-vnet.md
for better understanding

**Comment by daemon1024** [comment]
@sayantani11 Apologies for the delay and missing providing updates here.

So I went through the shared resources and the spec provided here https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml

I came with a rough configuration...

---
    Existing subnet

    ```yaml
    apiVersion: infrastructure.cluster.x-k8s.io/v1Alpha4
    kind: GCPCluster
    spec:
        network:
            autoCreateSubnetworks: false
            name: my-vpc
            subnets:
                - name: my-subnet
                cidrBlock: 10.0.32.0/20
        project: xyz
        region: us-easta
    ```

    New subnet, provide cidrblock

    ```yaml
    apiVersion: infrastructure.cluster.x-k8s.io/v1Alpha4
    kind: GCPCluster
    spec:
        network:
            autoCreateSubnetworks: false
            name: my-vpc
            subnets:
                - name: my-subnet
                cidrBlock: 10.0.32.0/20
                region: ? # do we need it when we have region specified in spec?
        project: xyz
        region: us-easta
    ```

    Auto cidr block ranges - https://cloud.google.com/vpc/docs/vpc#ip-ranges
---

But I am not sure how do I test it out!  I don't have GCP instance 😓
