### ISSUE TITLE
Allow creation of zonal clusters in addition to (multi-zone) regional ones

### ISSUE THREAD

**Issue by itspngu** [kubernetes-sigs/cluster-api-provider-gcp#444]
/kind feature

**Describe the solution you'd like**
Currently, the GCPCluster resource accepts a `region` input, allowing users to specify the GCP region to provision the control plane and nodes in. Using the following configuration, I get 1x control plane and 3x worker nodes in the `europe-west3-a` zone:

```yaml
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: test
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: test-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: GCPCluster
    name: test
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: GCPCluster
metadata:
  name: test
spec:
  network:
    name: default
  project: XXXX
  region: europe-west3
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: test-control-plane
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: GCPMachineTemplate
    name: test-control-plane
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: gce
        timeoutForControlPlane: 20m
      controllerManager:
        extraArgs:
          allocate-node-cidrs: "false"
          cloud-provider: gce
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: gce
        name: '{{ ds.meta_data.local_hostname.split(".")[0] }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: gce
        name: '{{ ds.meta_data.local_hostname.split(".")[0] }}'
  replicas: 1
  version: 1.20.9
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: GCPMachineTemplate
metadata:
  name: test-control-plane
spec:
  template:
    spec:
      instanceType: n1-standard-2
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: test-md-0
spec:
  clusterName: test
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: test-md-0
      clusterName: test
      failureDomain: europe-west3-a
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: GCPMachineTemplate
        name: test-md-0
      version: 1.20.9
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: GCPMachineTemplate
metadata:
  name: test-md-0
spec:
  template:
    spec:
      instanceType: n1-standard-2
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: test-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: gce
          name: '{{ ds.meta_data.local_hostname.split(".")[0] }}'
```

```shell_session
$ gcloud compute instances list --filter="tags.items=test"
NAME                          ZONE            MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP  STATUS
test-control-plane-6q88b  europe-west3-a  n1-standard-2               10.156.0.69               RUNNING
test-md-0-cwrpj           europe-west3-a  n1-standard-2               10.156.0.25               RUNNING
test-md-0-rj8n7           europe-west3-a  n1-standard-2               10.156.0.12               RUNNING
test-md-0-xt24p           europe-west3-a  n1-standard-2               10.156.0.14               RUNNING
```

I would like to, in some shape or form, be able to specify which zones are used for cluster resources, e.g. "provision both control plane and workers *only* in europe-west3-b" or "provision 3 control plane nodes in west3-a, -b and -c, and provision one pool of workers per zone", etc.

**Anything else you would like to add:**
The relevant portion of the controller appears to be https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/controllers/gcpcluster_controller.go#L176, but changes would also have to be introduced to the CRDs. How exactly this should be implemented is probably a topic for debate.
