### ISSUE TITLE
Cannot create VMs for Machines. /root/.kube/config missing

### ISSUE THREAD

**Issue by oxddr** [kubernetes-sigs/cluster-api-provider-gcp#66]
I've created cluster from HEAD. Initial machines as defined in `machines.yaml` have been created succesfully. However when I tried to create Machinset [1], VMs for underlying Machines have not been created. Based on logs, it seems there is a problem while genering kubeadm token:

```
E1130 12:14:10.410996       1 machineactuator.go:785] unable to create token: exit status 1 [failed to load admin kubeconfig [open /root/.kube/config: no such file or directory]    
```

[1] 
```
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineSet
metadata:
  name: ms3
spec:
  replicas: 3
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerConfig:
        value:
          apiVersion: "gceproviderconfig/v1alpha1"
          kind: "GCEMachineProviderConfig"
          roles:
          - Node
          zone: "us-central1-f"
          machineType: "n1-standard-1"
          os: "ubuntu-1604-lts"
          disks:
          - initializeParams:
            diskSizeGb: 30
            diskType: "pd-standard"
      versions:
        kubelet: 1.12.0
```
