### ISSUE TITLE
Pod CIDR of cluster does not match input from Cluster spec

### ISSUE THREAD

**Issue by bubbaksmith** [kubernetes-sigs/cluster-api-provider-gcp#895]
/kind bug

**What steps did you take and what happened:**
After generating a quickstart GKE cluster, the pod CIDR of the cluster does not match the input from `Cluster.spec.clusterNetwork.pods.cidrBlocks`.

```shell
kind create cluster -n local

export EXP_CAPG_GKE=true
export EXP_MACHINE_POOL=true
clusterctl init --infrastructure gcp

GCP_B64ENCODED_CREDENTIALS=$(cat /Users/bubba/dev/capi/service-account.json | base64 | tr -d '\n') \
  GCP_REGION=us-central1 \
  GCP_PROJECT=internal-dev-123456 \
  GCP_NETWORK_NAME=kubernetes \
  clusterctl generate cluster vanilla --flavor gke > gke-vanilla.yaml

kubectl apply -f gke-vanilla.yaml
cluster.cluster.x-k8s.io/vanilla created
gcpmanagedcluster.infrastructure.cluster.x-k8s.io/vanilla created
gcpmanagedcontrolplane.infrastructure.cluster.x-k8s.io/vanilla-control-plane created
machinepool.cluster.x-k8s.io/vanilla-mp-0 created
gcpmanagedmachinepool.infrastructure.cluster.x-k8s.io/vanilla-mp-0 created

kubectl get cluster vanilla -o yaml | yq ".spec.clusterNetwork"
pods:
  cidrBlocks:
    - 192.168.0.0/16
    
gcloud container clusters describe default-vanilla-control-plane --region us-east4 | yq ".ipAllocationPolicy"
clusterIpv4Cidr: 10.0.0.0/14
clusterIpv4CidrBlock: 10.0.0.0/14
clusterSecondaryRangeName: gke-default-vanilla-control-plane-pods-e3331177
podCidrOverprovisionConfig: {}
servicesIpv4Cidr: 10.4.0.0/20
servicesIpv4CidrBlock: 10.4.0.0/20
servicesSecondaryRangeName: gke-default-vanilla-control-plane-services-e3331177
stackType: IPV4
useIpAliases: true
```

Here is the manifest YAML
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vanilla
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPManagedControlPlane
    name: vanilla-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPManagedCluster
    name: vanilla
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedCluster
metadata:
  name: vanilla
  namespace: default
spec:
  network:
    name: kubernetes
  project: internal-dev-123456
  region: us-east4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: vanilla-control-plane
  namespace: default
spec:
  location: us-east4
  project: internal-dev-123456
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: vanilla-mp-0
  namespace: default
spec:
  clusterName: vanilla
  replicas: 0
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: vanilla
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPManagedMachinePool
        name: vanilla-mp-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedMachinePool
metadata:
  name: vanilla-mp-0
  namespace: default
spec: {}
```

![Screenshot 2023-04-13 at 9 39 29 AM](https://user-images.githubusercontent.com/3159228/231776814-e573bb4c-bf0b-4ec7-ab3a-9aac1a1e168f.png)

**What did you expect to happen:**
I expected the pod CIDR from the `Cluster` spec to match the pod CIDR of the cluster after creation. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v1.4.1
- CAPG version: v1.3.0
- Minikube/KIND version: kind v0.16.0 go1.19.1 darwin/arm64
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
- OS (e.g. from `/etc/os-release`): MacOS 13.2.1 (22D68) - Darwin Kernel Version 22.3.0
